"""
Population Health Demo — SYNTHETIC data aggregation.

Every number returned by this module describes app/generate_synthetic_
population.py's fabricated dataset (synthetic_patients / synthetic_
encounters tables), never real patients. This is a deliberately separate
module from app/analytics.py, which computes the *real* governance
dashboard and explicitly refuses to show any patient/encounter figure —
see that module's own docstring. Keeping these two completely apart in
code (separate module, separate tables, separate router, separate
frontend page) means the real dashboard's honesty guarantee can never be
silently compromised by this one.

Every function here returns an "is_synthetic": True field and the same
disclaimer string, and every table it reads carries an is_synthetic column
in its own schema — so even a raw SQL query against the database, not just
the API, makes the fabrication status obvious.
"""
import sqlite3
from typing import Any, Dict, List

DB_PATH = "db/ayush_icd11_combined.db"

DISCLAIMER = (
    "SYNTHETIC DEMONSTRATION DATA. These patients, encounters, and demographics were "
    "generated by scripts/generate_synthetic_population.py and do not describe any real "
    "person. This view exists to illustrate what a population-health dashboard would show "
    "at realistic volume — it is not derived from and must never be presented as real "
    "usage data. See app/analytics.py for this service's real, live-computed metrics."
)


def _conn() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def _table_exists(cur, name: str) -> bool:
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (name,))
    return cur.fetchone() is not None


def is_available() -> bool:
    """False until scripts/generate_synthetic_population.py has been run."""
    conn = _conn()
    cur = conn.cursor()
    available = _table_exists(cur, "synthetic_patients")
    if available:
        cur.execute("SELECT COUNT(*) AS n FROM synthetic_patients")
        available = cur.fetchone()["n"] > 0
    conn.close()
    return available


def overview() -> Dict[str, Any]:
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute("SELECT COUNT(*) AS n FROM synthetic_patients")
        total_patients = cur.fetchone()["n"]
        cur.execute("SELECT COUNT(*) AS n FROM synthetic_encounters")
        total_encounters = cur.fetchone()["n"]
        cur.execute("SELECT MIN(encounter_date) AS a, MAX(encounter_date) AS b FROM synthetic_encounters")
        span = cur.fetchone()
        cur.execute("SELECT COUNT(DISTINCT region) AS n FROM synthetic_patients")
        region_count = cur.fetchone()["n"]

        return {
            "is_synthetic": True,
            "disclaimer": DISCLAIMER,
            "total_patients": total_patients,
            "total_encounters": total_encounters,
            "date_range": {"from": span["a"], "to": span["b"]},
            "regions_covered": region_count,
        }
    finally:
        conn.close()


def by_gender() -> List[Dict[str, Any]]:
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute("SELECT gender, COUNT(*) AS n FROM synthetic_patients GROUP BY gender ORDER BY n DESC")
        return [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()


def by_age_band() -> List[Dict[str, Any]]:
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute("SELECT age_band, COUNT(*) AS n FROM synthetic_patients GROUP BY age_band")
        rows = {r["age_band"]: r["n"] for r in cur.fetchall()}
        order = ["0-17", "18-29", "30-44", "45-59", "60-74", "75+"]
        return [{"age_band": b, "n": rows.get(b, 0)} for b in order]
    finally:
        conn.close()


def by_region() -> List[Dict[str, Any]]:
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute(
            """SELECT p.region AS region, COUNT(DISTINCT p.id) AS patients, COUNT(e.id) AS encounters
               FROM synthetic_patients p LEFT JOIN synthetic_encounters e ON e.patient_id = p.id
               GROUP BY p.region ORDER BY patients DESC"""
        )
        return [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()


def by_month() -> List[Dict[str, Any]]:
    """Encounter volume per calendar month — the 'time' axis of the demo."""
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute(
            """SELECT SUBSTR(encounter_date, 1, 7) AS month, COUNT(*) AS n
               FROM synthetic_encounters GROUP BY month ORDER BY month ASC"""
        )
        return [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()


def by_tradition() -> List[Dict[str, Any]]:
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute("SELECT tradition, COUNT(*) AS n FROM synthetic_encounters GROUP BY tradition ORDER BY n DESC")
        return [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()


_TRADITION_TERM_TABLE = {
    "Ayurveda": ("nam", "namc_code", "namc_term", "name_english"),
    "Siddha": ("nsm", "namc_code", "namc_term", None),
    "Unani": ("num", "numc_code", "numc_term", None),
}


def _term_display(cur, tradition: str, code: str) -> str:
    table, code_col, term_col, eng_col = _TRADITION_TERM_TABLE[tradition]
    select_cols = f"{term_col}" + (f", {eng_col}" if eng_col else "")
    cur.execute(f"SELECT {select_cols} FROM {table} WHERE {code_col} = ? LIMIT 1", (code,))
    row = cur.fetchone()
    if not row:
        return code
    if eng_col and row[eng_col]:
        return f"{row[term_col]} ({row[eng_col]})"
    return row[term_col] or code


def top_conditions_national(limit: int = 10) -> List[Dict[str, Any]]:
    """
    The national ranking a Ministry dashboard actually wants: which NAMASTE
    codes show up most often across the whole synthetic population, with
    the real term displayed (the code is real NAMASTE data; only the
    encounter volume behind it is synthetic).
    """
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute(
            """SELECT tradition, namaste_code, COUNT(*) AS n
               FROM synthetic_encounters GROUP BY tradition, namaste_code
               ORDER BY n DESC LIMIT ?""",
            (limit,),
        )
        rows = cur.fetchall()
        return [
            {
                "tradition": r["tradition"],
                "namaste_code": r["namaste_code"],
                "display": _term_display(cur, r["tradition"], r["namaste_code"]),
                "encounters": r["n"],
            }
            for r in rows
        ]
    finally:
        conn.close()


def top_conditions_by_region(limit_per_region: int = 3) -> List[Dict[str, Any]]:
    """
    Answers "which condition is most common in which region" — the
    region-level drill-down a government analyst would use to target
    outreach or resource allocation. Still 100% synthetic patient/encounter
    volume; the codes and their real terms are genuine NAMASTE data.
    """
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute(
            """SELECT p.region AS region, e.tradition AS tradition, e.namaste_code AS namaste_code, COUNT(*) AS n
               FROM synthetic_encounters e JOIN synthetic_patients p ON p.id = e.patient_id
               GROUP BY p.region, e.tradition, e.namaste_code
               ORDER BY p.region, n DESC"""
        )
        rows = cur.fetchall()
        by_region: Dict[str, List[Dict[str, Any]]] = {}
        for r in rows:
            bucket = by_region.setdefault(r["region"], [])
            if len(bucket) >= limit_per_region:
                continue
            bucket.append({
                "tradition": r["tradition"],
                "namaste_code": r["namaste_code"],
                "display": _term_display(cur, r["tradition"], r["namaste_code"]),
                "encounters": r["n"],
            })
        return [{"region": region, "top_conditions": conditions} for region, conditions in by_region.items()]
    finally:
        conn.close()


def gender_by_region() -> List[Dict[str, Any]]:
    """Cross-tab: gender split within each region — a real ask for a government demographic view."""
    conn = _conn()
    cur = conn.cursor()
    try:
        cur.execute(
            """SELECT region, gender, COUNT(*) AS n FROM synthetic_patients
               GROUP BY region, gender ORDER BY region, gender"""
        )
        rows = [dict(r) for r in cur.fetchall()]
        pivoted: Dict[str, Dict[str, Any]] = {}
        for r in rows:
            pivoted.setdefault(r["region"], {"region": r["region"]})[r["gender"]] = r["n"]
        return list(pivoted.values())
    finally:
        conn.close()


def full_demo_payload() -> Dict[str, Any]:
    if not is_available():
        return {
            "is_synthetic": True,
            "available": False,
            "disclaimer": DISCLAIMER,
            "message": "Synthetic dataset not generated yet. Run: python scripts/generate_synthetic_population.py",
        }
    return {
        "is_synthetic": True,
        "available": True,
        "disclaimer": DISCLAIMER,
        "overview": overview(),
        "by_gender": by_gender(),
        "by_age_band": by_age_band(),
        "by_region": by_region(),
        "by_month": by_month(),
        "by_tradition": by_tradition(),
        "gender_by_region": gender_by_region(),
        "top_conditions_national": top_conditions_national(10),
        "top_conditions_by_region": top_conditions_by_region(3),
    }
